### ISSUE TITLE
I dont understand

### ISSUE THREAD

**Issue by xGamerx11** [skeeto/vulkan-test#3]
When i open the program. Its shows me a Failure and tells me:
Vulkan drivers installed and funcotioning but are incompatible. An instace could not be created.
So i dont understand what it means.

**Comment by skeeto** [comment]
It just means vkCreateInstance() failed. The program doesn't actually 
investigate as to why it failed and just prints that error. Either I 
made a mistake in one of the parameters when creating a Vulkan instance 
(likely) or your Vulkan driver is faulty.

**Comment by xGamerx11** [comment]
I think i dont have a vulkan driver.
